[default]
exten => 1002,1,NoOp(--- Incoming Call ---)
   same => n,Answer()
   same => n,Wait(1)  ; Give time for client to sync
   same => n,Playback(hello-world,noanswer)  ; Ensure playback starts fresh
   same => n,Hangup()
exten => 1001,1,NoOp(Starting ExternalMedia Call)
   same => n,Stasis(index)  ; Hand off control to ARI
   same => n,Hangup()
