[default]
exten => 1002,1,NoOp(--- Incoming Call ---)
   same => n,Answer()
   same => n,Wait(1)  ; Give time for client to sync
   same => n,Playback(hello-world,noanswer)  ; Ensure playback starts fresh
   same => n,Hangup()
exten => 1001,1,NoOp(Starting ExternalMedia Call)
   same => n,Stasis(index)  ; Hand off control to ARI
   same => n,Hangup()
exten => 1003,1,NoOp(Calling SIP/1003)
   same => n,Dial(SIP/1003,30)  ; Ring SIP/1003 for 30 seconds
   same => n,Hangup()
exten => 1000,1,NoOp(Calling SIP/1000)
   same => n,Dial(SIP/1000,30)  ; Ring SIP/1000 for 30 seconds
   same => n,Hangup()
