[global]
user_agent=Asterisk PJSIP

[transport-udp]
type=transport
protocol=udp
type=transport
protocol=udp
bind=0.0.0.0:5060
# local_net=192.168.1.0/24
# external_media_address=192.168.1.218
# external_signaling_address=192.168.1.218

[endpoint-1000]
type=endpoint
context=default
disallow=all
allow=ulaw
auth=auth-1000
aor=1000
direct_media=no

[auth-1000]
type=auth
auth_type=userpass
password=your_password
username=1000

[aor-1000]
type=aor
max_contacts=1

[endpoint-1003]
type=endpoint
context=default
disallow=all
allow=ulaw
auth=auth-1003
aor=1003
direct_media=no

[auth-1003]
type=auth
auth_type=userpass
password=your_password
username=1003

[aor-1003]
type=aor
max_contacts=1
