[global]
user_agent=Asterisk PJSIP

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
# local_net=172.31.0.0/20
# external_media_address=63.176.174.46
# external_signaling_address=63.176.174.46
allow_reload=yes

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060

[1000]  ; Endpoint for User 1000
type=endpoint
context=default
disallow=all
allow=ulaw
auth=auth-1000
aors=aor-1000
direct_media=no

[auth-1000]  ; Authentication for User 1000
type=auth
auth_type=userpass
password=SuperSecurePassword
username=1000

[aor-1000]  ; Contact for User 1000
type=aor
max_contacts=1

[1003]  ; Endpoint for User 1003
type=endpoint
context=default
disallow=all
allow=ulaw
auth=auth-1003
aors=aor-1003
direct_media=no

[auth-1003]  ; Authentication for User 1003
type=auth
auth_type=userpass
password=AnotherSecurePassword
username=1003

[aor-1003]  ; Contact for User 1003
type=aor
max_contacts=1
