[general]
localnet=127.0.0.1/255.255.255.0  ; Define your local network
externip=192.168.100.222
nat=force_rport,comedia  ; Helps with NAT traversal
directmedia=no  ; Ensures Asterisk handles media correctly
context=default           ; Default context for incoming calls
bindaddr=0.0.0.0          ; Listen on all IP addresses
allow=ulaw                ; Allow G.711 u-law codec
allow=alaw                ; Allow G.711 a-law codec

[1000]
type=friend
host=dynamic
secret=your_password
context=default
disallow=all
allow=ulaw
allow=alaw
canreinvite=no
nat=force_rport,comedia

# [1002]
# type=friend
# host=dynamic              ; The softphone will register
# secret=your_password      ; Replace with a strong password
# context=default           ; Match the dialplan context
