[general]
localnet=192.168.1.0/24,192.168.64.0/24
externip=192.168.1.106
nat=force_rport,comedia  ; Helps with NAT traversal
directmedia=no  ; Ensures Asterisk handles media correctly
context=default           ; Default context for incoming calls
bindaddr=0.0.0.0          ; Listen on all IP addresses
allow=ulaw                ; Allow G.711 u-law codec
# allow=alaw                ; Allow G.711 a-law codec

[1000]
type=friend
host=dynamic
secret=your_password
context=default
disallow=all
allow=ulaw
# allow=alaw
canreinvite=no
nat=force_rport,comedia
directmedia=no


[1003]
type=friend
host=dynamic
secret=your_password
context=default
disallow=all
allow=ulaw
# allow=alaw
canreinvite=no
nat=force_rport,comedia
directmedia=no
